import "./globals.css";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";

import {
  ColorSchemeScript,
  createTheme,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";

// const inter = Inter({ subsets: ["latin"] });
const theme = createTheme({
  fontFamily: "Inter, sans-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <NavBar />
          <main className="p-5"> {children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}
